### ISSUE TITLE
Vensim Bit Size

### ISSUE THREAD

**Issue by MelissaK4** [pbreach/venpy#21]
I have 64bit Vensim will this work if I use 64bit python? I've downloaded but when I try to import a model I get that the bits don't match (sorry if this isn't the right place to post this question).

**Comment by tonyvsuk** [comment]
If you have 64 bit Vensim, then yes, you need 64 bit Python as well.

**Comment by MelissaK4** [comment]
When I use 64bit python I get this error, %64bit version of Python will not work with vendll32.dll. So I then tried 32bit python and I get, %Could not find Vensim DLL 'vendll32.dll' . I'm guessing the issue isn't my bits but the location of 'vendll32.dll'. Do you know where I find it?

**Comment by tonyvsuk** [comment]
Try modifying your code so it loads vendll64.dll instead of the 32 bit DLL.

**Comment by MelissaK4** [comment]
Do you know which file I need to modify it in?

**Comment by MelissaK4** [comment]
I found the code and adjusted it, I no longer get the error thanks.
